name: Update readme ⭐️ progress

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    update-readme:
        runs-on: ubuntu-latest
        if: ${{ vars.AOC_ENABLED == 'true' }}
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            - name: Set up cargo cache
              uses: actions/cache@v3
              continue-on-error: false
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
                  restore-keys: ${{ runner.os }}-cargo-
            - uses: k2bd/advent-readme-stars@v1
              with:
                  userId: ${{ secrets.AOC_USER_ID }}
                  sessionCookie: ${{ secrets.AOC_SESSION }}
                  year: ${{ secrets.AOC_YEAR }}
            - run: cargo all --release --time
            - uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "chore(README): update solution tables"
